services:
#  rest-api:
#    image: nisarg/demo-rest:1.0.0
#    ports:
#      - "8080:8080"
#    networks:
#      - app-network
#    volumes:
#      - ../logs:/workspace/logs
#    environment:
#      # JDBC settings for Spring Boot
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/peopledb
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=postgres
#      - BPL_HEAP_PERCENT=75
#      - SPRING_PROFILES_ACTIVE=local
#    depends_on:
#      - postgres

  postgres:
    container_name: postgres
    networks:
      - app-network
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=peopledb'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6432:5432'
    volumes:
        - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  loki:
    networks:
      - app-network
    image: grafana/loki:2.9.6
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
      - loki-config:/etc/loki
    # Loki ships with a working local-config.yaml in the image

  promtail:
    networks:
      - app-network
    image: grafana/promtail:2.9.6
    command: -config.expand-env=true -config.file=/etc/promtail/promtail-config.yml
    volumes:
      # Map your app logs directory into the container read-only
      - ../logs:/var/log/app:ro
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml:ro
      - promtail-positions:/positions
    depends_on:
      - loki

  grafana:
    networks:
        - app-network
    image: grafana/grafana:11.1.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana
      # Optional: auto-provision Loki datasource
      - grafana-provisioning:/etc/grafana/provisioning

volumes:
  loki-data:
  loki-config:
  grafana-data:
  promtail-positions:
  grafana-provisioning:
  pgdata:
  logs:

networks:
  app-network:
    driver: bridge