server:
  http_listen_port: 9080
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: app-json
    static_configs:
      - targets: [localhost]
        labels:
          job: "local-app"
          app: "dcir-api"
          env: "dev"
          __path__: /app/logs/app-json*.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            logger: logger
            message: message
            correlationId: correlationId
            traceId: traceId
            spanId: spanId